site:
  title: Embassy Docs
  start_page: embassy::index.adoc

content:
  sources:
    - url: https://github.com/embassy-rs/embassy.git
      branches: book-poc
      start_path: docs
ui: 
  bundle:
    url: https://github.com/embassy-rs/embassy-antora-ui/releases/download/0.2.1/ui-bundle.zip
    snapshot: true

output:
  clean: true
runtime:
  fetch: true

