name: Publish
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch: { }

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
      - run: make

      - name: Publish
        shell: bash
        run: |
          mkdir -p ~/.kube
          echo "${{secrets.KUBECONFIG}}" > ~/.kube/config
          kubectl config view
          POD=$(kubectl -n embassy get po -l app=website -o jsonpath={.items[0].metadata.name})
          mv build/site build/book
          kubectl cp build/book $POD:/usr/share/nginx/html