name: Publish
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch: { }

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
      - run: make

      - name: Deploy GH pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/site

      - name: Install embassy-dev SSH Key
        shell: bash
        env:
          SSH_KEY: ${{secrets.WEBSITE_SSH_KEY}}
        run: |
          mkdir -p ~/.ssh
          echo -n "$SSH_KEY" > ~/.ssh/website.key
          chmod 0600 ~/.ssh/website.key
          stat -l ~/.ssh/website.key

      - name: Deploy embassy dev
        run: rsync -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/website.key" -avz ./build/site/ embassy@embassy.dev:.
